version: 2

sources:
  - name: xn_raw
    description: 'raw information for sources'
    database: xeneta_db
    schema:  xn_raw
    tables:
      - name: ports
        description: 'Information about cargo ports'
      - name: regions
        description: 'Information about cargo regions'   
      - name: exchange_rate
        description: 'Information about exchange rate for day'  
      - name: XS_DATAPOINTS_1
        description: 'Information about internal datapoints'   
      - name: XS_CHARGES_1
        description: 'Information about charges'  
       
